/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  docs: [
    'quick-start',
    {
      type: 'category',
      label: 'RASM APIs',
      collapsed: false,
      items: [
        'system',
        'arithmetic',
        'comparison',
        'logical',
        'control-flow',
        'pointers'
      ],
    },
    {
      type: 'category',
      label: 'Robot APIs',
      collapsed: false,
      items: [
        'robots/robot-arm-vacuum-gripper',
        'robots/robot-arm-spot-welder',
        'robots/robot-arm-painter',
        'robots/conveyor-belt',
        'robots/scanner',
        'robots/laser-sensor',
        'robots/turret',
        'robots/cartesian-laser-cutter',
        'robots/pallet-crane'
      ],
    }
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
